### ISSUE TITLE
plotting functions not working

### ISSUE THREAD

**Issue by bholden7** [easystats/see#54] opened 2019-11-05 19:25 UTC
**Describe the bug**
can't reproduce many of the plots from: https://easystats.github.io/see/articles/bayestestR.html, eg, priors = TRUE doesn't work; p_significance not working either, yields: Error in plot.window(...) : need finite 'xlim' values

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
I expected to be able to reproduce the [see?] plots but cannot

**Screenshots**
<img width="654" alt="Screen Shot 2019-11-05 at 2 24 31 PM" src="https://user-images.githubusercontent.com/44203517/68238902-ff6e9700-ffd7-11e9-9f6c-4b88a9d694c3.png">

**Specifiations (please complete the following information):**
 everything is 100% up to date

**Comment by strengejacke** [comment] 2019-11-05 19:34
I assume you are using the CRAN packages? The plots you see on the website can be reproduced with the latest see version from GitHub. However, a CRAN submission is planned very soon.

**Comment by bholden7** [comment] 2019-11-05 19:38
I used the GitHub version (devtools::install_github("easystats/see”) and still doesn’t work.



Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by strengejacke** [comment] 2019-11-05 19:42
Can you post your session info?

**Comment by bholden7** [comment] 2019-11-05 19:46
When I run this:
install.packages("devtools")
devtools::install_github("easystats/see")

library("see”)

I get a message that there is no package called ’see’ (and the CRAN version doesn’t reproduce the plots).


Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by bholden7** [comment] 2019-11-05 19:51
Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by DominiqueMakowski** [comment] 2019-11-05 23:56
Could you try 1) closing R 2) reopening R 3) running `devtools::install_github("easystats/see")` 4) see if installation finished or 'exited if 0' or something, in which case post the error message here? Thanks!

**Comment by bholden7** [comment] 2019-11-06 13:02
Hi. It appears to install, ie, no messages when finished, only a prompt (>). But when I try library(see) I get the message that there is no package called see:



These are the error messages:

* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘rlang’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rlang’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rlang’
installation of package ‘rlang’ had non-zero exit status* installing *source* package ‘digest’ ...
** package ‘digest’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘digest’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/digest’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/digest’
installation of package ‘digest’ had non-zero exit status
The downloaded source packages are in
	‘/private/var/folders/66/6yy31gvd2ggdrcmn0v72j0z40000gn/T/RtmpvfuZdz/downloaded_packages’
✔  checking for file ‘/private/var/folders/66/6yy31gvd2ggdrcmn0v72j0z40000gn/T/RtmpvfuZdz/remotes3a124037b69/easystats-see-99f2770/DESCRIPTION’ ...
─  preparing ‘see’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘see/docs’
   Removed empty directory ‘see/man/figures’
   Removed empty directory ‘see/pkgdown’
─  building ‘see_0.2.1.1.tar.gz’
   
ERROR: dependency ‘effectsize’ is not available for package ‘see’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/see’
installation of package ‘/var/folders/66/6yy31gvd2ggdrcmn0v72j0z40000gn/T//RtmpvfuZdz/file3a12e1caf7e/see_0.2.1.1.tar.gz’ had non-zero exit status

Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by bholden7** [comment] 2019-11-06 13:24
Tried again and got this:

Error: Failed to install 'see' from GitHub:
  (converted from warning) installation of package ‘/var/folders/66/6yy31gvd2ggdrcmn0v72j0z40000gn/T//RtmpvfuZdz/file3a1dfbafa9/see_0.2.1.1.tar.gz’ had non-zero exit status


Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by strengejacke** [comment] 2019-11-06 14:48
Sorry for the inconvenience, but some of the packages are undergoing larger revisions and restucturing, that's why you get all these errors.

Due to package dependencies, you may need to install other packages as well. I suggest you install packages step-by-step in the following order:

From CRAN

```r
install.packages("insight")
install.packages("bayestestR")
install.packages("performance")
```

From GitHub

```r
devtools::install_github("easystats/parameters")
devtools::install_github("easystats/effectsize")
devtools::install_github("easystats/see")
```

The _effectsize_ package is submitted to, but not yet released on CRAN. _see_ will be updated short afer _effectsize_ is on CRAN. And _parameters_ should also work with the CRAN version, but the GitHub version includes some new features that are also already supported by the _see_ package.


If you have the patience, you could then also install the remaining packages from GitHub:

```r
devtools::install_github("easystats/estimate")
devtools::install_github("easystats/correlation")
devtools::install_github("easystats/report")
devtools::install_github("easystats/easystats")
```

Once this is done, you can (hopefully) easily load all packages with `library(easystats)`, and update _all_ latest GitHub versions (when you think this is necessary) with `easystats::install_easystats_latest()`.

**Comment by bholden7** [comment] 2019-11-06 16:26
Hi.
Thanks for this.
Everything loaded (apparently) without problem except, of course (sorry), for library(easystats).
This was the error message:

Error: package or namespace load failed for ‘easystats’: .onAttach failed in attachNamespace() for 'easystats', details: call: NULL error: package or namespace load failed for ‘insight’ in get(method, envir = home): lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/insight/R/insight.rdb' is corrupt


Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by strengejacke** [comment] 2019-11-06 16:30
> '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/insight/R/insight.rdb' is corrupt

This seems to be a different issue, probably the install from insight failed? Can't say exactly, but I think removing the insight-package and re-installing it might fix this as well...

But does _see_ work now?

**Comment by bholden7** [comment] 2019-11-06 16:33
Exactly correct. I reinstalled insight and did library(easystats) and now (keeping fingers crossed) it works!
A pain in the ass but the programs are really great and incredibly useful. 
Thanks so much for persevering and keep up the fantastic work!


Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Closed** 2019-11-14 08:46 UTC
